// Create a function ft_fibonacci that returns the n-th element of the Fibonacci sequence, the first element being at the 0 index.
// We’ll consider that the Fibonacci sequence starts like this: 0, 1, 1, 2.
// Obviously, ft_fibonacci has to be recursive.
// If the index is less than 0, the function should return -1.

// The Fibonacci Sequence is the series of numbers:
// 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...

// The next number is found by adding up the two numbers before it.
// The 2 is found by adding the two numbers before it (1+1)
// The 3 is found by adding the two numbers before it (1+2), And the 5 is (2+3)

// The Fibonacci numbers are generated by setting F0=0, F1=1, and then using the recursive formula
// Fn = Fn-1 + Fn-2

#include <stdio.h>

int ft_fibonacci(int index)
{
    if (index < 0)
    {
        return (-1);
    }
    if (index <= 2)
    {
        return (index);
    }
    return ft_fibonacci(index - 1) + ft_fibonacci(index - 2);
}

int main()
{
    int index;

    index = 5;
    printf("%d",ft_fibonacci(index));
}


